name: "Bug Report"
description: "Report a bug that needs to be fixed"
title: "Bug: "
labels: ["bug"]
assignees: []
projects: ["Screeps"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Relevant environment details (OS, browser, version, etc.)
      placeholder: |
        - OS: [e.g. Windows 10, macOS 12.1, Ubuntu 20.04]
        - Browser: [e.g. Chrome 95, Firefox 93]
        - Version: [e.g. 1.2.3]
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.
    validations:
      required: false