blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: Bug Report
    description: For recording bugs that need to be fixed
    labels: [bug]
    template: bug.yml
  - name: Feature Request
    description: New or reworked functionality
    labels: [feature]
    template: feature.yml