name: "Feature Request"
description: "Request new or reworked functionality"
title: "Feature: "
labels: ["feature"]
assignees: []
projects: ["Screeps"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature do you want and why?
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any acceptance criteria, mockups, references, etc.
    validations:
      required: false